//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace uddiClient.com.capescience.www {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    [System.Web.Services.WebServiceBindingAttribute(Name="AirportWeatherBinding", Namespace="http://www.capeclear.com/AirportWeather.wsdl")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WeatherSummary))]
    public class AirportWeather : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public AirportWeather() {
            this.Url = "http://www.capescience.com/ccgw/GWXmlServlet";
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getLocation", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getLocation(string arg0) {
            object[] results = this.Invoke("getLocation", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetLocation(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLocation", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getWind", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getWind(string arg0) {
            object[] results = this.Invoke("getWind", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetWind(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getWind", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetWind(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getSkyConditions", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getSkyConditions(string arg0) {
            object[] results = this.Invoke("getSkyConditions", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetSkyConditions(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSkyConditions", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetSkyConditions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getVisibility", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getVisibility(string arg0) {
            object[] results = this.Invoke("getVisibility", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetVisibility(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getVisibility", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetVisibility(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getTemperature", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getTemperature(string arg0) {
            object[] results = this.Invoke("getTemperature", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetTemperature(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getTemperature", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetTemperature(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getPressure", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getPressure(string arg0) {
            object[] results = this.Invoke("getPressure", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetPressure(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPressure", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetPressure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getHumidity", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getHumidity(string arg0) {
            object[] results = this.Invoke("getHumidity", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetHumidity(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHumidity", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetHumidity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getSummary", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public WeatherSummary getSummary(string arg0) {
            object[] results = this.Invoke("getSummary", new object[] {
                        arg0});
            return ((WeatherSummary)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetSummary(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSummary", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public WeatherSummary EndgetSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((WeatherSummary)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("capeconnect:AirportWeather:com.capeclear.weatherstation.Station#getOb", RequestNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station", ResponseNamespace="capeconnect:AirportWeather:com.capeclear.weatherstation.Station")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getOb(string arg0) {
            object[] results = this.Invoke("getOb", new object[] {
                        arg0});
            return ((string)(results[0]));
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public System.IAsyncResult BegingetOb(string arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getOb", new object[] {
                        arg0}, callback, asyncState);
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        public string EndgetOb(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    [System.Xml.Serialization.SoapTypeAttribute("WeatherSummary", "http://www.capeclear.com/AirportWeather.xsd")]
    public class WeatherSummary {
        
        public string location;
        
        public string wind;
        
        public string sky;
        
        public string temp;
        
        public string humidity;
        
        public string pressure;
        
        public string visibility;
    }
}
